# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  BUILD_NUMBER = 1
  #APP_VERSION = "0.6"
  APP_VERSION = "0.7"
  # APP_IDENTIFIER = "com.prasthana.feedbackapp"
  APP_IDENTIFIER = "com.prasthana.oneononetalks"
  APP_NAME = "Feedback"
  XCODE_PROJECT = "Runner.xcodeproj"
  XCODE_WORKSPACE = "Runner.xcworkspace"
  XCODE_SCHEME = "Runner"

  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Set the App Version
    increment_version_number( version_number: APP_VERSION,xcodeproj: XCODE_PROJECT)
    # Increment the build number
    BUILD_NUMBER = latest_testflight_build_number(app_identifier: APP_IDENTIFIER,version: APP_VERSION) + 1
    increment_build_number(build_number: BUILD_NUMBER,xcodeproj: XCODE_PROJECT)
    
    api_key = app_store_connect_api_key(
      key_id: ENV["APPSTORE_KEY_ID"],
      issuer_id: ENV["APPSTORE_ISSUER_ID"],
      key_filepath: ENV["APPSTORE_KEY_FILEPATH"]
    )
    match(type: "adhoc",app_identifier: APP_IDENTIFIER,api_key: api_key)

    gym(scheme: XCODE_SCHEME,
        output_name: APP_NAME + APP_VERSION + "(" + BUILD_NUMBER.to_s + ")" + ".ipa",
        include_symbols: true)

    upload_to_testflight(skip_submission: true,
                         skip_waiting_for_build_processing: true,
                         api_key: api_key)


  end
end
