# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  BUILD_NUMBER = 2
  APP_VERSION = "0.6"

#   lane :increment_staging do
#     staging_build_number = google_play_track_version_codes(
#         package_name:  ENV["PACKAGE_NAME"],
#         track: "internal",
#         json_key: ENV["JSON_FILE"],
#       )[0]

#     current_staging_build_number = staging_build_number + 1
#     build_number = increment_version_code(gradle_file_path: "app/build.gradle", version_code: current_staging_build_number)
# end

  desc "Submit a new Beta Build to Playstore"
  lane :beta do


    gradle(
      tasks: ["clean bundleRelease"],
      properties: { "android.injected.version.code" => BUILD_NUMBER, 
                    "android.injected.version.name" => APP_VERSION, }
    )

    upload_to_play_store(
      skip_upload_apk: true, 
      package_name: ENV["PACKAGE_NAME"],
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      track: "internal",
      release_status: 'draft',
      json_key: ENV["JSON_FILE"])

  end

end
